-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 11:29:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema managementsystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `managementsystem` ;

-- -----------------------------------------------------
-- Schema managementsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `managementsystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `managementsystem` ;

-- -----------------------------------------------------
-- Table `managementsystem`.`empbook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`empbook` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`empbook` (
  `empId` INT NOT NULL,
  `empName` VARCHAR(50) NOT NULL,
  `empPassword` VARCHAR(50) NOT NULL,
  `empSex` VARCHAR(50) NOT NULL,
  `empDepartment` VARCHAR(100) NOT NULL,
  `empDeptno` INT NOT NULL,
  `empJob` VARCHAR(50) NOT NULL,
  `levelId` INT NOT NULL default 1,
  `hireDate` DATETIME NOT NULL default current_timestamp,
  `salary` INT NOT NULL default 28000,
  `overTimeLeftHour` INT NOT NULL DEFAULT 46,
  `overTimeTotalHour` INT NOT NULL DEFAULT 46,
  `takeoffTotalHours` INT NOT NULL DEFAULT 56,
  `empAcator` VARCHAR(1000) NULL default '/images/default_user.jpg',
  PRIMARY KEY (`empId`),
  UNIQUE INDEX `empName` (`empName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `managementsystem`.`checkIn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`checkIn` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`checkIn` (
  `checkInId` INT NOT NULL AUTO_INCREMENT,
  `empId` INT NOT NULL,
  `checkInTime` DATETIME NULL DEFAULT current_timestamp,
  `checkOutTime` DATETIME NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`checkInId`),
  INDEX `checkInList_empId_idx` (`empId` ASC) VISIBLE,
  CONSTRAINT `checkInList_empId`
    FOREIGN KEY (`empId`)
    REFERENCES `managementsystem`.`empbook` (`empId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `managementsystem`.`form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`form` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`form` (
  `formId` VARCHAR(100) NOT NULL,
  `type` INT NOT NULL comment '1:takeoff(請假) 2:overtime(加班)',
  `applier` INT NOT NULL,
  `applyDate` DATETIME NOT NULL default current_timestamp,
  PRIMARY KEY (`formId`),
  INDEX `form_empId_idx` (`applier` ASC) VISIBLE,
  CONSTRAINT `form_applier`
    FOREIGN KEY (`applier`)
    REFERENCES `managementsystem`.`empbook` (`empId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `managementsystem`.`overtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`overtime` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`overtime` (
  `formId` VARCHAR(100) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `applyHour` INT NOT NULL default 0,
  `overtimeType` INT NOT NULL DEFAULT 2 comment '1:加班 2:補休',
  `dayOrHoilday` INT NOT NULL DEFAULT 1 comment '1:平日 2:假日',
  `reason` VARCHAR(200) NOT NULL,
  `verifyState` INT NOT NULL default 2 comment '0:未通過 1:通過 2:審核中',
  `checkReason` VARCHAR(200) NULL DEFAULT NULL,
  INDEX `overtime_formId_idx` (`formId` ASC) VISIBLE,
  PRIMARY KEY (`formId`),
  CONSTRAINT `overtime_formId`
    FOREIGN KEY (`formId`)
    REFERENCES `managementsystem`.`form` (`formId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `managementsystem`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`service` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`service` (
  `serviceId` INT NOT NULL auto_increment,
  `levelId` INT NOT NULL default 1 comment '1:員工 2:主管',
  `serviceLocation` VARCHAR(1000) NOT NULL,
  `serviceSubject` VARCHAR(1000) NOT NULL,
  `serviceName` VARCHAR(100) NOT NULL,
  `serviceUrl` VARCHAR(1000) NOT NULL,
  `sort` INT NOT NULL,
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `managementsystem`.`takeoff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`takeoff` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`takeoff` (
  `formId` VARCHAR(100) NOT NULL,
  `agent` INT NOT NULL comment '代理人',
  `takeoffType` INT NOT NULL comment '1:特休 2:事假 3:病假 4:喪假 5:公假',
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `reason` VARCHAR(200) NOT NULL,
  `verifyState` INT NOT NULL default 2 comment '0:未通過 1:通過 2:審核中',
  `checkReason` VARCHAR(200) NULL DEFAULT NULL,
  `takeoffDay` INT NOT NULL DEFAULT 0,
  `takeoffHour` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`formId`),
  INDEX `takeoff_agent_idx` (`agent` ASC) VISIBLE,
  CONSTRAINT `takeoff_formId`
    FOREIGN KEY (`formId`)
    REFERENCES `managementsystem`.`form` (`formId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `takeoff_agent`
    FOREIGN KEY (`agent`)
    REFERENCES `managementsystem`.`empbook` (`empId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `managementsystem`.`attachement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`attachement` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`attachement` (
  `attachId` INT NOT NULL auto_increment,
  `form_id` VARCHAR(100) NOT NULL,
  `filePath` VARCHAR(1000) NOT NULL,
  `createTime` DATETIME NOT NULL default current_timestamp,
  `updateTime` DATETIME NULL default current_timestamp on update current_timestamp,
  PRIMARY KEY (`attachId`),
  INDEX `attachement_form_id_idx` (`form_id` ASC) VISIBLE,
  CONSTRAINT `attachement_form_id`
    FOREIGN KEY (`form_id`)
    REFERENCES `managementsystem`.`form` (`formId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `managementsystem`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `managementsystem`.`salary` ;

CREATE TABLE IF NOT EXISTS `managementsystem`.`salary` (
  `id` INT NOT NULL auto_increment,
  `empId` INT NOT NULL,
  `basicAmonut` INT NOT NULL default 28000,
  `takeoffAmount` INT NOT NULL default 0,
  `overtimeAmount` INT NOT NULL default 0,
  `totalAmount` INT NOT NULL default 0,
  `salaryDate` DATETIME NOT NULL default current_timestamp,
  `createDate` DATETIME NULL default current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `salary_empId_idx` (`empId` ASC) VISIBLE,
  CONSTRAINT `salary_empId`
    FOREIGN KEY (`empId`)
    REFERENCES `managementsystem`.`empbook` (`empId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
